Repository SwevenSoftware/BlockCOVID-web, pull requests merged in 2021-06, with the labels that each got.

#142 Fixed dates and times 'to' and 'from' UTC format as server requested
  src/actions/reportActions.ts
  src/actions/roomsActions.ts
  src/components/ModifyRoomComponent.tsx
  src/components/NewRoomComponent.tsx
  src/components/ReportsComponent.tsx
  src/components/RoomsComponent.tsx
Labels: bug

#143 Incr-Prenotazioni
  dist/index.html
  package.json
  public/index.html
  src/Api/reportAPI.ts
  src/App.tsx
  src/DotGrid.tsx
  src/GeneralLayout.tsx
  src/actions/reportActions.ts
  src/actions/roomsActions.ts
  src/components/DeleteAccountComponent.tsx
  src/components/DeleteRoomComponent.tsx
  src/components/ModifyAccountComponent.tsx
  src/components/ModifyRoomComponent.tsx
  src/components/NewRoomComponent.tsx
  src/components/ReportsComponent.tsx
  src/components/RoomsComponent.tsx
  src/components/StatusRoomComponent.tsx
  src/reducers/handlers/loginHandlers.ts
  src/reducers/handlers/reportHandlers.ts
  src/reducers/reportReducer.ts
  src/reducers/rootReducer.ts
  src/styles.css
  src/types.ts
  test/Actions/ReportActions.test.ts
  test/Api/ReportApi.test.ts
  test/Components/ReportsComponent.test.tsx
  test/Reducers/ReportsReducer.test.ts
Labels: Increment

#144 Fixed datetime for report generation
  src/actions/reportActions.ts
Labels: bug

#145 Feature/title report cards
  src/components/ReportsComponent.tsx
  src/styles.css
Labels: CSS

#147 Removed password constraint when modifying account, password may be empty
  src/Api/accountAPI.ts
  src/components/ModifyAccountComponent.tsx
Labels: enhancement

#146 Added user weekly reservations calendar on account page
  package.json
  src/Api/reservationAPI.ts
  src/actions/accountsActions.ts
  src/actions/reservationsActions.ts
  src/components/AccountsComponent.tsx
  src/components/CalendarViewComponent.tsx
  src/reducers/handlers/reservationsHandlers.ts
  src/reducers/reservationsReducer.ts
  src/reducers/rootReducer.ts
  src/styles.css
  src/types.ts
  test/Actions/ReservationActions.test.ts
  test/Api/ReservationApi.test.ts
  test/Components/AccountsComponent.test.tsx
  test/Components/CalendarViewComponent.test.tsx
  test/Reducers/ReservationsReducer.test.ts
Labels: enhancement

#148 Corrected typo(s) in README
  README.md
Labels: bug

#149 Added hashcode view and transaction hashcode view in report cards
  src/Api/reportAPI.ts
  src/components/ReportsComponent.tsx
  src/styles.css
Labels: CSS, enhancement

#150 Incr-Utilizzo
  README.md
  package.json
  src/Api/accountAPI.ts
  src/Api/reportAPI.ts
  src/Api/reservationAPI.ts
  src/actions/accountsActions.ts
  src/actions/reportActions.ts
  src/actions/reservationsActions.ts
  src/components/AccountsComponent.tsx
  src/components/CalendarViewComponent.tsx
  src/components/ModifyAccountComponent.tsx
  src/components/ReportsComponent.tsx
  src/reducers/handlers/reservationsHandlers.ts
  src/reducers/reservationsReducer.ts
  src/reducers/rootReducer.ts
  src/styles.css
  src/types.ts
  test/Actions/ReservationActions.test.ts
  test/Api/ReservationApi.test.ts
  test/Components/AccountsComponent.test.tsx
  test/Components/CalendarViewComponent.test.tsx
  test/Reducers/ReservationsReducer.test.ts
Labels: Increment

#151 end'
  jest.config.js
  package.json
  src/App.tsx
  src/CardGrid.tsx
  test/CardGrid.test.tsx
  test/DotGrid.test.tsx
Labels: enhancement
