Repository SwevenSoftware/BlockCOVID-web, pull requests merged in 2021-05, with the labels that each got.

#45 Fixed API with new latest server update
  package.json
  src/api.ts
Labels: bug

#49 Feature/fix develop 5984858
  src/NewUser.tsx
  src/api.ts
  src/components/NewUserComponent.tsx
  src/reducers/newUserReducer.ts
  src/reducers/rootReducer.ts
  src/types.ts
Labels: bug

#50 Implemented logout API
  src/actions/loginActions.ts
  src/api.ts
  src/components/NewUserComponent.tsx
  src/reducers/loginReducer.ts
  src/types.ts
Labels: bug

#53 Feature/ci
  .github/workflows/build-bundle.yml
  .gitignore
  README.md
  jest.config.js
  package.json
  pre-commit.sh
  src/Accounts.tsx
  src/App.tsx
  src/CardGrid.tsx
  src/DotGrid.tsx
  src/GeneralLayout.tsx
  src/Login.tsx
  src/NewUser.tsx
  src/Pencil.tsx
  src/Report.tsx
  src/Reservation.tsx
  src/Room.ts
  src/SearchUsers.tsx
  src/Token.ts
  src/Trash.tsx
  src/actions/accountsActions.ts
  src/actions/loginActions.ts
  src/actions/newUserActions.ts
  src/actions/trashActions.ts
  src/api.ts
  src/components/AccountsComponent.tsx
  src/components/LoginComponent.tsx
  src/components/NewUserComponent.tsx
  src/components/PencilComponent.tsx
  src/components/TrashComponent.tsx
  src/configureStore.ts
  src/index.tsx
  src/reducers/accountsReducer.ts
  src/reducers/loginReducer.ts
  src/reducers/newUserReducer.ts
  src/reducers/rootReducer.ts
  src/reducers/trashReducer.ts
  src/test/DotGrid.test.ts
  src/test/LoginActions.test.ts
  src/theme.tsx
  src/types.ts
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: documentation, enhancement, refactor

#54 moved reducer switch logic to an handler logic
  src/actions/accountsActions.ts
  src/actions/loginActions.ts
  src/actions/newUserActions.ts
  src/actions/trashActions.ts
  src/reducers/accountsReducer.ts
  src/reducers/handlers/accountHandlers.ts
  src/reducers/handlers/loginHandlers.ts
  src/reducers/handlers/newUserHandlers.ts
  src/reducers/handlers/trashHandlers.ts
  src/reducers/loginReducer.ts
  src/reducers/newUserReducer.ts
  src/reducers/reducerFactory.tsx
  src/reducers/trashReducer.ts
  src/types.ts
Labels: enhancement, refactor

#55 Traslated pencil to redux, fixed dashboard delay
  .github/workflows/build-bundle.yml
  .gitignore
  README.md
  package.json
  pre-commit.sh
  src/actions/pencilActions.ts
  src/api.ts
  src/components/AccountsComponent.tsx
  src/components/PencilComponent.tsx
  src/components/TrashComponent.tsx
  src/reducers/accountsReducer.ts
  src/reducers/handlers/accountHandlers.ts
  src/reducers/pencilReducer.ts
Labels: bug, enhancement, to-redux

#56 Fixed rerender on accounts page after each operation
  src/actions/accountsActions.ts
  src/actions/newUserActions.ts
  src/actions/pencilActions.ts
  src/actions/trashActions.ts
  src/components/NewUserComponent.tsx
  src/components/PencilComponent.tsx
  src/components/TrashComponent.tsx
  src/reducers/accountsReducer.ts
  src/reducers/handlers/accountHandlers.ts
  src/reducers/handlers/newUserHandlers.ts
  src/reducers/handlers/trashHandlers.ts
  src/reducers/newUserReducer.ts
  src/reducers/pencilReducer.ts
  src/reducers/reducerFactory.tsx
  src/reducers/rootReducer.ts
  src/reducers/trashReducer.ts
  src/types.ts
Labels: bug

#62 Feature/rooms
  src/Accounts.tsx
  src/App.tsx
  src/CardGrid.tsx
  src/DotGrid.tsx
  src/GeneralLayout.tsx
  src/Images/x_red.png
  src/Login.tsx
  src/NewUser.tsx
  src/Pencil.tsx
  src/Report.tsx
  src/Reservation.tsx
  src/Room.ts
  src/SearchUsers.tsx
  src/Token.ts
  src/Trash.tsx
  src/components/AccountsComponent.tsx
  src/components/NewUserComponent.tsx
  src/styles.css
  src/theme.tsx
Labels: enhancement, refactor

#63 Incr-Account
  .github/workflows/build-bundle.yml
  .gitignore
  README.md
  jest.config.js
  package.json
  pre-commit.sh
  src/.babelrc
  src/App.tsx
  src/CardGrid.tsx
  src/DotGrid.tsx
  src/GeneralLayout.tsx
  src/Login.tsx
  src/Report.tsx
  src/Reservation.tsx
  src/Room.ts
  src/Token.ts
  src/actions/accountsActions.ts
  src/actions/loginActions.ts
  src/api.ts
  src/components/AccountsComponent.tsx
  src/components/LoginComponent.tsx
  src/components/NewUserComponent.tsx
  src/components/PencilComponent.tsx
  src/components/TrashComponent.tsx
  src/configureStore.ts
  src/index.tsx
  src/reducers/accountsReducer.ts
  src/reducers/handlers/accountHandlers.ts
  src/reducers/handlers/loginHandlers.ts
  src/reducers/loginReducer.ts
  src/reducers/reducerFactory.tsx
  src/reducers/rootReducer.ts
  src/styles.css
  src/sweven.keys/sweven.crt.pem
  src/sweven.keys/sweven.key.pem
  src/sweven.keys/sweven.p12
  src/test/DotGrid.test.ts
  src/test/LoginActions.test.ts
  src/theme.tsx
  src/types.ts
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: Increment

#64 Added room view with room's rapresentation and horizontal tabs
  src/CardGrid.tsx
  src/DotGrid.tsx
  src/Room.ts
  src/Rooms.tsx
  src/Tabs.tsx
Labels: enhancement

#67 Added api method for room creation
  src/api.ts
  src/components/AccountsComponent.tsx
Labels: enhancement

#105 Removed checks on tokenID
  src/actions/roomsActions.ts
Labels: bug

#68 init Dockerfile
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  nginx.conf
  public/index.html
  src/api.ts
  src/react-app-env.d.ts
Labels: enhancement

#109 Created Modal standard for deletion and modify Rooms
  src/CardGrid.tsx
  src/DotGrid.tsx
  src/components/CardGridComponent.tsx
  src/components/DeleteRoomComponent.tsx
  src/components/RoomsComponent.tsx
Labels: DeleteRoom, ModifyRoom, enhancement

#111 Refactored parameters in api methods and action methods
  src/Api/accountAPI.ts
  src/Api/roomAPI.ts
  src/GeneralLayout.tsx
  src/actions/accountsActions.ts
  src/actions/loginActions.ts
  src/actions/roomsActions.ts
  src/components/AccountsComponent.tsx
  src/components/DeleteAccountComponent.tsx
  src/components/DeleteRoomComponent.tsx
  src/components/LoginComponent.tsx
  src/components/ModifyAccountComponent.tsx
  src/components/ModifyRoomComponent.tsx
  src/components/NewAccountComponent.tsx
  src/components/NewRoomComponent.tsx
  src/components/RoomsComponent.tsx
  src/reducers/handlers/loginHandlers.ts
  src/reducers/loginReducer.ts
  src/test/Api/AccountApi.test.ts
  src/types.ts
Labels: bug, refactor

#110 fix missing files in code coverage
  .babelrc
  README.md
  jest.config.js
  src/.babelrc
  tsconfig.json
Labels: refactor

#112 Added grid in modification modal and added cleaner grid button with its style
  src/CardGrid.tsx
  src/DotGrid.tsx
  src/components/ModifyRoomComponent.tsx
  src/styles.css
Labels: ModifyRoom, enhancement

#114 Feature/new room creation
  .github/workflows/coverage.yml
  Dockerfile
  docker-compose.yml
  nginx.conf
  package.json
  public/index.html
  src/components/NewAccountComponent.tsx
  src/components/NewRoomComponent.tsx
  src/types.ts
  tsconfig.json
Labels: NewRoom, enhancement

#116 Fixed `npm start` fail due "Error: spawn ENOENT"
  package.json
Labels: bug

#118 Added view of room list in rooms page
  codecov.yml
  src/actions/roomsActions.ts
  src/components/RoomsComponent.tsx
  src/reducers/handlers/roomsHandlers.ts
  test/Reducers/RoomReducer.test.ts
Labels: RoomsComponent, enhancement

#120 Feature/handle confirm delete room component
  codecov.yml
  src/components/DeleteRoomComponent.tsx
Labels: DeleteRoom, enhancement

#121 getRooms uses right params
  src/Api/roomAPI.ts
  test/Api/RoomApi.test.ts
Labels: bug

#122 Added undefined type if requested room list is empty
  src/reducers/handlers/roomsHandlers.ts
Labels: bug

#124 Fixed room deletion modal and its dispatch
  src/DotGrid.tsx
  src/components/DeleteRoomComponent.tsx
  src/components/ModifyRoomComponent.tsx
  src/components/RoomsComponent.tsx
Labels: bug

#123 Added desk api calls
  src/Api/roomAPI.ts
  src/actions/roomsActions.ts
  src/components/ModifyRoomComponent.tsx
  src/components/NewRoomComponent.tsx
  src/reducers/handlers/roomsHandlers.ts
  src/types.ts
  test/Actions/RoomActions.test.ts
  test/Api/RoomApi.test.ts
  test/Reducers/RoomReducer.test.ts
Labels: enhancement

#126 Implementation of room modification modal, fix of grid behaviour (desks)
  CSSStub.js
  jest.config.js
  src/Api/roomAPI.ts
  src/DotGrid.tsx
  src/Grid.ts
  src/actions/roomsActions.ts
  src/components/DeleteAccountComponent.tsx
  src/components/DeleteRoomComponent.tsx
  src/components/ModifyRoomComponent.tsx
  src/components/NewAccountComponent.tsx
  src/components/NewRoomComponent.tsx
  src/components/RoomsComponent.tsx
  src/index.tsx
  src/reducers/handlers/roomsHandlers.ts
  src/styles.css
  src/types.ts
  test/Api/RoomApi.test.ts
  test/Components/RoomsComponent.test.tsx
Labels: ModifyRoom, enhancement

#128 Fixed room modification modal re-rendering
  src/components/ModifyRoomComponent.tsx
  src/components/RoomsComponent.tsx
Labels: bug

#129 Fixed opening and closing time in room creation and modification modals
  src/components/ModifyRoomComponent.tsx
  src/components/NewRoomComponent.tsx
Labels: bug

#135 Added reports page
  package.json
  src/Api/reportAPI.ts
  src/App.tsx
  src/GeneralLayout.tsx
  src/actions/reportActions.ts
  src/components/DeleteAccountComponent.tsx
  src/components/DeleteRoomComponent.tsx
  src/components/ModifyAccountComponent.tsx
  src/components/ModifyRoomComponent.tsx
  src/components/ReportsComponent.tsx
  src/reducers/handlers/reportHandlers.ts
  src/reducers/reportReducer.ts
  src/reducers/rootReducer.ts
  src/styles.css
  src/types.ts
  test/Actions/ReportActions.test.ts
  test/Api/ReportApi.test.ts
  test/Components/ReportsComponent.test.tsx
  test/Reducers/ReportsReducer.test.ts
Labels: enhancement

#137 removed old files, removed unnecessary links in the navigator
  dist/index.html
  public/index.html
  src/GeneralLayout.tsx
Labels: refactor

#138 Corrected month in timestamp date. Rooms and theirs desk are fetch correctly
  src/actions/roomsActions.ts
Labels: bug

#139 Fixed room desks legend text
  src/components/StatusRoomComponent.tsx
  src/styles.css
Labels: bug

#140 Added desk(s) information on room status modal
  src/components/StatusRoomComponent.tsx
  src/reducers/handlers/loginHandlers.ts
Labels: enhancement
